version: '3.7'

services:
  coderr.server.web:
    image: coderrio/coderrserverweb
    build:
      context: .
      dockerfile: Coderr.Server.Web/Dockerfile
    networks:
      - coderr_network

volumes:
  esdata:
    driver: local

networks:
  coderr_network:
    name: coderr_network