version: "3.7"

services:

  coderr-server-web:
    image: "coderrio/coderrserverweb:latest"
    container_name: coderr-server-web
    hostname: coderr-server-web
    ports:
      - "2500:80"
    networks:
      - coderr_network

volumes:
  esdata:
    driver: local

networks:
  coderr_network:
    name: coderr_network